class OrderStatus

  PAYABLE = 'PAYABLE'
  TO_DELIVER = 'TO_DELIVER'
  REFUND_PENDING = 'REFUND_PENDING'
  REFUNDED = 'REFUNDED'
  DELIVERED = 'DELIVERED'
  TO_COMMENT = 'TO_COMMENT'
  COMPLETED = 'COMPLETED'
  CANCELLED = 'CANCELLED'
  COMPLAIN = 'COMPLAIN'



end